name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: live

      - uses: actions/download-artifact@v2
        with:
          name: kennste-dist

      - name: Display structure of downloaded files
        run: ls -R
