name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: live

      - uses: dawidd6/action-download-artifact@v2
        with:
          name: kennste-dist
          workflow: main.yml

      - name: Display structure of downloaded files
        run: ls -R

      - uses: EndBug/add-and-commit@v7
        with:
          branch: live
          message: 'publish application to GitHub pagese(live branch)'
          tag: 'v1.0.0 --force'

